apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mydep
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      run: mydep
  template:
    metadata:
      labels:
        run: mydep
    spec:
      containers:
      - command:
        - sleep
        - 1000s
        image: busybox
        name: mydep
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
      schedulerName: my-scheduler
